spring:
  datasource:
    url: jdbc:p6spy:mysql://47.98.49.140:3306/mp
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource