spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3366/xp?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
    type: com.zaxxer.hikari.HikariDataSource