spring:
  datasource:
    url: jdbc:mysql://47.98.49.140:3310/mp?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: 159669
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource