spring:
  datasource:
    url: jdbc:mysql://47.98.49.140:3310/mp
    username: root
    password: 159669
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
server:
  servlet:
    context-path: /api/power